#!/usr/bin/env python3
"""
Slack Configuration Helper
Interactive script to help users set up Slack integration
"""

import os
import sys

def get_user_input(prompt, default=None):
    """Get user input with optional default value"""
    if default:
        user_input = input(f"{prompt} [{default}]: ").strip()
        return user_input if user_input else default
    else:
        user_input = input(f"{prompt}: ").strip()
        return user_input

def setup_slack_config():
    """Interactive setup for Slack configuration"""
    
    print("🔧 Slack Integration Configuration Helper")
    print("=" * 50)
    print()
    
    print("This script will help you configure Slack integration for DAST reporting.")
    print("You can choose between two methods:")
    print("1. Slack Bot Token (Recommended - more features)")
    print("2. Slack Webhook URL (Simpler setup)")
    print()
    
    # Choose method
    while True:
        method = get_user_input("Choose method (1 for Bot Token, 2 for Webhook)", "1")
        if method in ['1', '2']:
            break
        print("Please enter 1 or 2")
    
    config_lines = [
        "# Slack Configuration for DAST Reporting",
        "# Generated by setup script",
        ""
    ]
    
    if method == '1':
        print("\n📱 Setting up Slack Bot Token method:")
        print("1. Go to https://api.slack.com/apps")
        print("2. Create a new app or use existing one")
        print("3. Go to 'OAuth & Permissions'")
        print("4. Add scopes: chat:write, chat:write.public")
        print("5. Install app to workspace")
        print("6. Copy the Bot User OAuth Token (starts with xoxb-)")
        print()
        
        bot_token = get_user_input("Enter your Slack Bot Token (xoxb-...)")
        if not bot_token.startswith('xoxb-'):
            print("⚠️  Warning: Bot token should start with 'xoxb-'")
        
        channel = get_user_input("Enter Slack channel", "#security-alerts")
        if not channel.startswith('#'):
            channel = f"#{channel}"
        
        config_lines.extend([
            f"SLACK_BOT_TOKEN={bot_token}",
            f"SLACK_CHANNEL={channel}",
            "",
            "# Webhook URL (leave empty when using bot token)",
            "# SLACK_WEBHOOK_URL="
        ])
        
        print(f"\n✅ Bot token method configured!")
        print(f"   Channel: {channel}")
        
    else:
        print("\n🪝 Setting up Slack Webhook method:")
        print("1. Go to https://api.slack.com/apps")
        print("2. Create a new app or use existing one")
        print("3. Go to 'Incoming Webhooks'")
        print("4. Activate incoming webhooks")
        print("5. Add new webhook to workspace")
        print("6. Select channel and copy webhook URL")
        print()
        
        webhook_url = get_user_input("Enter your Slack Webhook URL")
        if not webhook_url.startswith('https://hooks.slack.com/'):
            print("⚠️  Warning: Webhook URL should start with 'https://hooks.slack.com/'")
        
        config_lines.extend([
            f"SLACK_WEBHOOK_URL={webhook_url}",
            "",
            "# Bot token (leave empty when using webhook)",
            "# SLACK_BOT_TOKEN=",
            "# SLACK_CHANNEL="
        ])
        
        print(f"\n✅ Webhook method configured!")
    
    # Add common configuration
    config_lines.extend([
        "",
        "# ZAP Report Configuration",
        "ZAP_REPORT_PATH=report.json",
        "",
        "# GitHub Integration (automatically set by GitHub Actions)",
        "# GITHUB_PR_NUMBER="
    ])
    
    # Write configuration file
    config_content = "\n".join(config_lines)
    
    print(f"\n📝 Configuration:")
    print("-" * 30)
    print(config_content)
    print("-" * 30)
    
    # Ask if user wants to save
    save = get_user_input("\nSave configuration to .env file? (y/n)", "y")
    
    if save.lower() in ['y', 'yes']:
        with open('.env', 'w') as f:
            f.write(config_content)
        print("✅ Configuration saved to .env file")
        print("⚠️  Remember to add .env to your .gitignore file!")
    else:
        print("Configuration not saved. You can copy the above content manually.")
    
    # GitHub Secrets reminder
    print(f"\n🔐 GitHub Secrets Setup:")
    print("For CI/CD integration, add these secrets to your GitHub repository:")
    print("Go to: Repository Settings → Secrets and variables → Actions")
    
    if method == '1':
        print(f"- SLACK_BOT_TOKEN: {bot_token}")
        print(f"- SLACK_CHANNEL (as variable): {channel}")
    else:
        print(f"- SLACK_WEBHOOK_URL: {webhook_url}")
    
    print(f"\n🧪 Testing:")
    print("Run 'python test_slack_integration.py' to test your configuration")
    
    return True

def check_existing_config():
    """Check if configuration already exists"""
    if os.path.exists('.env'):
        print("⚠️  Found existing .env file")
        overwrite = get_user_input("Overwrite existing configuration? (y/n)", "n")
        return overwrite.lower() in ['y', 'yes']
    return True

def main():
    """Main function"""
    print("Welcome to the DAST Slack Integration Setup!")
    print()
    
    if not check_existing_config():
        print("Setup cancelled.")
        return
    
    try:
        setup_slack_config()
        print("\n🎉 Setup completed successfully!")
        print("\nNext steps:")
        print("1. Test your configuration: python test_slack_integration.py")
        print("2. Add secrets to GitHub repository")
        print("3. Commit and push your changes")
        print("4. Check the GitHub Actions workflow")
        
    except KeyboardInterrupt:
        print("\n\nSetup cancelled by user.")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Error during setup: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()