name: ZAP Full (Active) Scan
on:
  workflow_dispatch:

jobs:
  zap-full:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: https://dast-test-production.up.railway.app/
          rules_file_name: .zap/rules.tsv
          docker_name: ghcr.io/zaproxy/zaproxy:stable
          cmd_options: >-
            -a               # include alpha passive rules
            -r full-report.html
          allow_issue_writing: true
          fail_action: true
