name: OWASP ZAP Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
permissions:
  contents: read
  issues: write

jobs:
  zap_scan:
    name: ZAP Baseline Scan
    runs-on: ubuntu-latest

    steps:
      - name: ZAP Baseline Scan
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: 'https://dast-test-production.up.railway.app/'
          fail_action: false
          cmd_options: '-a'

      - name: Upload ZAP HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: zap_scan_html
          path: report_html.html

      - name: Upload ZAP Markdown Report
        uses: actions/upload-artifact@v4
        with:
          name: zap_scan_md
          path: report_md.md

      - name: Upload ZAP JSON Report
        uses: actions/upload-artifact@v4
        with:
          name: zap_scan_json
          path: report_json.json
